name: omnifixpos
description: "A new Flutter project for OmniFix POS."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # Firebase Packages
  firebase_core:
  firebase_auth:
  cloud_firestore:

  # Hive Packages
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Hive Generator Packages (Model / Adapter ထုတ်ရန်)
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true