import 'package:hive/hive.dart';

// Generated by Hive. Re-enable only after running the generator:
// flutter packages pub run build_runner build
// part 'shop_profile_model.g.dart';

@HiveType(typeId: 0)
class ShopProfileModel extends HiveObject {
  @HiveField(0)
  String shopName;

  @HiveField(1)
  String phoneNumber;

  @HiveField(2)
  String address;

  @HiveField(3)
  String slogan;

  @HiveField(4)
  String? logoPath;

  ShopProfileModel({
    required this.shopName,
    required this.phoneNumber,
    required this.address,
    required this.slogan,
    this.logoPath,
  });

  // Convert to Map (Optional for API or JSON export)
  Map<String, dynamic> toMap() {
    return {
      'shopName': shopName,
      'phoneNumber': phoneNumber,
      'address': address,
      'slogan': slogan,
      'logoPath': logoPath,
    };
  }

  // Create Object from Map
  factory ShopProfileModel.fromMap(Map<String, dynamic> map) {
    return ShopProfileModel(
      shopName: map['shopName'] ?? '',
      phoneNumber: map['phoneNumber'] ?? '',
      address: map['address'] ?? '',
      slogan: map['slogan'] ?? '',
      logoPath: map['logoPath'],
    );
  }
}